<a href="https://colab.research.google.com/github/reubence/Project-Euler/blob/master/Fibonacci_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem-2:** Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.**

In [4]:
def Even_Series(limit):
  if limit < 2:
    return 0
  no1 = 0
  no2 = 2
  sum = no1 + no2

  while no2 <=limit:
    no3 = 4* no2 + no1
    if (no3 > limit):
      break
    no1 = no2
    no2 = no3
    sum = sum + no2
  return sum

limit = 4000000
print(Even_Series(limit))

4613732